In [135]:
%matplotlib inline
import pandas as pd
import numpy as np
import scipy as sp

In [136]:
arr1 = np.arange(10)
arr2 = np.array([2,1,4])

In [137]:
randData = 2 + 3*np.random.randn(2,5)   # μ+σ*N(0,1)
randData

array([[ 6.26195239e+00, -4.41606941e-01,  3.59540371e-01,
         3.82671769e+00,  5.55447146e+00],
       [ 1.01395495e-03,  5.15828324e+00, -1.88601198e+00,
         8.28303688e+00,  6.06594279e+00]])

In [138]:
np.eye(3,3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [139]:
arr1=np.array([2,3])
arr2=np.array([2,-3])
arr1*arr2

array([ 4, -9])

In [140]:
names=np.array(['a', 'b', 'c', 'a', 'c'])

data=np.random.randn(5,6)
data


array([[-1.16237229, -0.34613443,  1.58003908, -0.48141968, -0.82151301,
         1.50750245],
       [ 0.3825482 ,  0.71629524, -0.77025994,  2.00808882, -0.14452988,
         1.00410978],
       [-0.6869671 , -1.0071689 , -0.04447391,  0.4512793 , -0.17193924,
        -0.28348272],
       [-0.46083025, -0.07217335, -0.5992859 , -1.77003491,  0.45970061,
         1.33293559],
       [ 0.01354537,  1.29673963,  0.49455461, -0.72706049,  0.74318143,
        -0.19230502]])

In [141]:
names=='a'

array([ True, False, False,  True, False])

In [142]:
data[names=='a']

array([[-1.16237229, -0.34613443,  1.58003908, -0.48141968, -0.82151301,
         1.50750245],
       [-0.46083025, -0.07217335, -0.5992859 , -1.77003491,  0.45970061,
         1.33293559]])

In [143]:
data=np.random.randn(4,7)
data

array([[-2.01817771,  0.26075983,  0.15380498, -0.33316347,  1.33600347,
         1.05596263,  0.34510375],
       [ 0.12819195, -1.16286041, -1.63856197, -1.06959253, -0.10956138,
         0.95952452,  0.7862915 ],
       [ 1.43465614,  1.45687879,  0.46922916, -0.28975204, -1.65998233,
         0.96356163, -0.31027918],
       [ 0.15427285, -1.41676089,  1.62033295, -1.15849047,  0.38032172,
         0.47023241,  0.08121353]])

In [144]:
data[0]

array([-2.01817771,  0.26075983,  0.15380498, -0.33316347,  1.33600347,
        1.05596263,  0.34510375])

In [145]:
data[0][1]

0.2607598331109806

In [146]:
data2=data[[0,2,1]]
data2

array([[-2.01817771,  0.26075983,  0.15380498, -0.33316347,  1.33600347,
         1.05596263,  0.34510375],
       [ 1.43465614,  1.45687879,  0.46922916, -0.28975204, -1.65998233,
         0.96356163, -0.31027918],
       [ 0.12819195, -1.16286041, -1.63856197, -1.06959253, -0.10956138,
         0.95952452,  0.7862915 ]])